# Description:
#   Ralph Wiggum Quotes
# Commands:
#   hubot wiggum - Retuns a Ralph Wiggum quote
module.exports = (robot) ->
  robot.respond /wiggum/i, (msg) ->
    quotes = [
      "What's lime disease?",
      "I'm going to eat chocolate 'til I barf!",
      "And, when the doctor said I didn't have worms any more, that was the happiest day of my life.",
      "My parents won't let me use scissors.",
      "So, do you...like...stuff?",
      "It says 'I Choo-choo-choose You,' and there's a picture of a train!",
      "The doctor said I wouldn't have so many nose bleeds if I kept my finger outta there.",
      "What's a battle?",
      "You're deceptive.",
      "Wheee! ...ow, I bit my tongue!",
      "I'm Idaho.",
      "My cat's name is mittens",
      "What's a diorama?",
      "I beat the smart kids! I beat the smart kids!",
      "I bent my wookie.",
      "My cat's breath smells like cat food.",
      "Principal Skinner, I got carsick in your office.",
      "Ow, my face is on fire!",
      "Somebody took my juice money!",
      "I won! I won!",
      "Me fail English? That's unpossible.",
      "Will you cook my dinner for me? My parents aren't around and I'm not allowed to turn on the stove.",
      "I'm a boy!",
      "Um, hi, Bart. I know you from school.",
      "Oh boy, sleep! That's where I'm a viking!",
      "When I grow up, I'm going to bovine university!",
      "I heard your dad went into a restaurant and ate everything in the restaurant and they had to close the restaurant.",
      "Was president Lincoln okay?",
      "That is sooo 1991.",
      "My neck hurts and my ear hurts. I have two owwies.",
      "I'm pedaling backwards!",
      "I heard a Frankenstein lives there!",
      "Hi, Lisa! We're going to be in a pie!",
      "Mrs. Krabappel and Principal Skinner were in the closet making babies and I saw one of the babies and the baby looked at me.",
      "My knob tastes funny.",
      "I dress myself!",
      "I think I wet my bed.",
      "Daddy, these rubber pants are hot.",
      "Look, big daddy, it's regular daddy.",
      "Maybe she drove to the moon.",
      "Which one is oral?",
      "No, Miss Hoover, I'm Ralph.",
      "Which one is one?",
      "Principal Skinner is an old man who lives at the school.",
      "Teacher made me go to Principal Skinner's office when I was dirty.",
      "When I grow up, I want to be a principal or a caterpillar.",
      "But you're suffering!",
      "Bye, witches! Thanks for not eating me!",
      "I'm special!",
      "Go, banana!",
      "I ated the purple berries",
      "It tastes like ... burning",
      "I found a moon rock in my nose!",
      "Hey, I know you, my daddy took your beer.",
      "Your hair is tall, and pretty!",
      "Help! She's touching my special area!",
      "My toys are all sticky.",
      "Slow down, Bart! My legs don't know how to be as long as yours.",
      "Bushes are nice 'cause they don't have prickers. Unless they do. This one did. Ouch!",
      "This is my sandbox, I'm not allowed to go in the deep end.",
      "That's where I saw the Leprchaun. He tells me to burn things!",
      "He's gonna smell like hot dogs.",
      "Maybe it's presents for all of us!",
      "Then, the doctor told me that BOTH my eyes were lazy! And that's why it was the best summer ever.",
      "This snowflake tastes like fishsticks.",
      "Is this my house?",
      "She's gonna say my name!",
      "Hi, Principal Skinner! Hi, Super Nintendo Chalmers!",
      "Somebody should iron you.",
      "Look, Daddy, a whale egg!",
      "You're King David! I love you 'cause you kill people.",
      "Daddy says I'm _this_ close to sleeping in the yard.",
      "And I want a bike and a monkey and a friend for the monkey.",
      "Eww, Daddy, this tastes like Gramma!",
      "I can't breathe good and it's making me sleepy.",
      "Mr. Flanders, you're blinded-ed.",
      "I fell out two times.",
      "Teacher, my shoes are making noise.",
      "My daddy shoots people!",
      "Lisa's bad dancing makes my feet sad.",
      "I ate too much plastic candy.",
      "Freeze, you crazy mommy!",
      "Mr. Army Man, I can't sleep without my Reggie Rabbit!",
      "Whee! I'm a pop sensation.",
      "I'm wearing a bathrobe, and I'm not even sick.",
      "Pop music's hard work.",
      "I can't read.",
      "I wanna twirl.",
      "His tummy sounds angry, daddy.",
      "We're a totem pole!",
      "I almost died.",
    ]
    msg.send msg.random quotes
